spring:
  application:
    name: SGMarket-Backend
  profiles:
    group:
      test: "test"
      local: "local, datasource, redis"
      dev: "dev, datasource, redis"
      prod: "prod, datasource, redis"
    include:
      - security
      - cloud
      - imp


swagger:
  url: ${SERVER_URL:http://localhost:8080}