spring:
  application:
    name: SGMarket-Backend
  profiles:
    group:
      test: "test"
      local: "local, datasource"
      dev: "dev, datasource"
      prod: "prod, datasource"
    include:
      - security
      - redis
      - cloud

swagger:
  url: ${SERVER_URL:http://localhost:8080}