spring:
  config:
    activate:
      on-profile: "prod"

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type: warn
