spring:
  config:
    activate:
      on-profile: "cloud"
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

storage:
  accessKey: ${AWS_ACCESS_KEY:}
  secretKey: ${AWS_SECRET_KEY:}
  bucket: ${S3_IMAGE_BUCKET:}
  region: ${AWS_REGION:ap-northeast-2}
